### PR TITLE
latest body regex support & extract callback function in separate util class for easier maintain

### PR DESCRIPTION
**Pull request by rusak47**
I've switched to tb91 and body regex is working flawlessly. On tb78 new solution works, but gives garbage for Cyrillic text, i.e. it's barely usable.

### CODE REVIEW

**Comment by RealRaven2000** [comment]
I need to review this near the end of the week with Github desktop as the diff is hard to see on the web interface...

**Comment by RealRaven2000** [comment]
There are a bunch of commits in there that are already in the code base - which makes it hard to see your changes -  can you recreate the PR  (rebase on current ESR78) and only check in your own changed filtaquilla.js?

**Comment by rusak47** [comment]
I'm new to git, so i hardly understand how to do it properly, but i believe i managed to do what you've asked. 
@RealRaven2000 I've merged all the latest changes from my side, so i suppose it should be ok now?

**Comment by rusak47** [comment]
https://github.com/RealRaven2000/FiltaQuilla/pull/114

**Pull request merged**
